apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stupidlb.fullname" . }}
  labels:
    {{- include "stupidlb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stupidlb.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stupidlb.fullname" . }}
    namespace: "{{.Release.Namespace}}"
