# Default values for stupidlb.
# This is a YAML-formatted file.

# CIDRs: List of CIDRs (or individual IP addresses) that the operator
# may assign to load balancers.  These are assumed to be dedicated for
# the use for load balancers.
#
# The operator will avoid assigning IP addresses which are already
# used by other load balancers; i.e. it is safe for users to
# explicitly specify an IP address on their load balancer from this
# range (assuming it is not already in use); the operator will then
# avoid assigning that IP address to other load balancers.
#
CIDRs: []
  # - 192.168.0.224/28
  # - 192.168.0.240/8

replicaCount: 1

image:
  repository: karljorgensen/stupidlb
  pullPolicy: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Command line options to supply to the operator. By default no
# options are required. This will accept the same options as "kopf
# run"
options: "--all-namespaces --log-format=json"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
# If affinity is not specified, the a default pod anti-affinity will be used to spread pods
defaultTopologyKey: kubernetes.io/hostname

priorityClassName: ""
runtimeClassName: ""
schedulerName: ""
